# This is a config for E2B sandbox template.
# You can use template ID (lwltsannu9hu8y6qaqv0) or template name (vedant-lovable-test-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vedant-lovable-test-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vedant-lovable-test-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vedant-lovable-test-1')

team_id = "797c8008-928d-47de-8a9c-ef75ca88e588"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vedant-lovable-test-1"
template_id = "lwltsannu9hu8y6qaqv0"
